#!/usr/bin/env node
/**
 * VERIFICATION HARNESS — runs the REAL AIOStreams stream-expression evaluator
 * (vendored in ./vendor) against this repo's `.expressions.json` profiles.
 *
 * It mirrors the real engine's `precomputeRankedStreamExpressions()` in
 * AIOStreams packages/core/src/streams/precomputer.ts:
 *   - builds a `StreamSelector` with an `ExpressionContext` whose `queryType`
 *     matches the guard on the expression
 *   - calls `selector.select(streams, expression)` for every enabled item
 *   - accumulates `score` into `streamExpressionScore` for matched streams
 *
 * The fixture stream is generated by running the profile's own `.regexes.json`
 * patterns against a realistic BluRay REMUX anime filename, so
 * `rankedRegexesMatched` (consumed by `regexMatched()`) is genuinely derived
 * from the profile rather than hand-picked.
 *
 * Exit code 0 on success, 1 on failure.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { StreamSelector } from './dist/vendor/streamExpression.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROFILES_DIR = join(__dirname, '..', '..', 'profiles');

// ---------------------------------------------------------------------------
// Fixture: a realistic Tier-1-equivalent BluRay REMUX anime release.
// ---------------------------------------------------------------------------
const REMUX_FILENAME =
  '[DemiHuman] Sousou no Frieren - 01 (1080p BluRay REMUX x265 10bit FLAC TrueHD 5.1) [ABC12345].mkv';

/** Build a minimal ParsedStream-shaped fixture from a filename. */
function buildFixtureStream(filename) {
  return {
    id: 'fixture-remux-01',
    type: 'debrid',
    addon: {
      instanceId: 'fixture',
      preset: { id: 'fixture', type: 'fixture', options: {} },
      manifestUrl: 'https://fixture.local/manifest.json',
      enabled: true,
      resources: ['stream'],
      name: 'fixture',
      timeout: 20000,
    },
    filename,
    folderName: '',
    parsedFile: {
      releaseGroup: 'SubsPlease',
      resolution: '1080p',
      quality: 'BluRay REMUX',
      encode: 'x265',
      audioChannels: ['5.1'],
      visualTags: ['10bit'],
      audioTags: ['TrueHD', 'FLAC'],
      languages: ['English', 'Japanese'],
      subtitle: undefined,
      seasonPack: false,
    },
    service: { id: 'realdebrid', cached: true },
    size: 4.2 * 1000 * 1000 * 1000, // ~4.2 GB
  };
}

// ---------------------------------------------------------------------------
// Run the profile's own regexes against the fixture filename, exactly like the
// real engine's ranked-regex pass sets `rankedRegexesMatched`.
// ---------------------------------------------------------------------------
function runProfileRegexes(regexes, fixture) {
  const matched = [];
  for (const { name, pattern } of regexes) {
    const m = /^\/(.+)\/([gimuyn]*)$/.exec(pattern);
    const re = m
      ? new RegExp(m[1], m[2].replace('n', ''))
      : new RegExp(pattern);
    if (
      (fixture.filename && re.test(fixture.filename)) ||
      (fixture.folderName && re.test(fixture.folderName))
    ) {
      matched.push(name);
    }
  }
  return matched;
}

// ---------------------------------------------------------------------------
// Evaluate a profile like the real precomputer: accumulate scores per stream.
//
// CRITICAL: the engine sets `parser.consts.queryType` from the *query* (an
// anime query carries queryType 'anime.movie' / 'anime.series'), then
// evaluates each expression string verbatim — the expression's own
// `queryType=='...' ? body : []` guard decides whether the body runs. So we
// evaluate every enabled expression under the profile's intended queryTypes,
// NOT under whatever guard the expression happens to contain. That is what
// makes this harness able to catch the regression: a profile gated on plain
// 'movie'/'series' yields score 0 under an anime query.
// ---------------------------------------------------------------------------
async function evaluateProfile(profilePath, intendedQueryTypes) {
  const items = JSON.parse(readFileSync(profilePath, 'utf8'));
  const regexesPath = profilePath.replace(/\.expressions\.json$/, '.regexes.json');
  const regexes = JSON.parse(readFileSync(regexesPath, 'utf8'));

  const fixture = buildFixtureStream(REMUX_FILENAME);
  fixture.rankedRegexesMatched = runProfileRegexes(regexes, fixture);

  const scoreByQt = {};
  const matchedCountByQt = {};
  let failures = 0;
  const failureDetails = [];

  for (const queryType of intendedQueryTypes) {
    const selector = new StreamSelector({ queryType, isAnime: true });
    let total = 0;
    let matchedCount = 0;
    for (const item of items) {
      if (item.enabled === false) continue;
      const { expression, score } = item;
      try {
        const selected = await selector.select([fixture], expression);
        if (selected.length > 0) {
          total += score ?? 0;
          matchedCount += 1;
        }
      } catch (error) {
        failures += 1;
        failureDetails.push(
          `[${queryType}] failed to evaluate: ${error.message}`
        );
      }
    }
    scoreByQt[queryType] = total;
    matchedCountByQt[queryType] = matchedCount;
  }

  return {
    profilePath,
    enabledItems: items.filter((i) => i.enabled !== false).length,
    regexesMatched: fixture.rankedRegexesMatched,
    scoreByQt,
    matchedCountByQt,
    failures,
    failureDetails,
  };
}

// ---------------------------------------------------------------------------
// Regression guard: the whole reason these profiles exist is that the anime
// expressions must be gated on `queryType=='anime.movie'`/`'anime.series'`.
// Under an anime query, the buggy plain `queryType=='movie'`/`'series'`
// guards must NOT fire (they were the regression e373b00 reintroduced).
// ---------------------------------------------------------------------------
async function checkAnimeGuards() {
  const fixture = buildFixtureStream(REMUX_FILENAME);
  fixture.rankedRegexesMatched = ['DemiHuman', '10bit'];

  let bad = 0;
  const checks = [
    {
      context: { queryType: 'anime.movie', isAnime: true },
      expr: `queryType=='movie' ? quality(streams, "BluRay REMUX") : []`,
      label: 'plain movie guard under anime.movie query',
    },
    {
      context: { queryType: 'anime.series', isAnime: true },
      expr: `queryType=='series' ? quality(streams, "BluRay REMUX") : []`,
      label: 'plain series guard under anime.series query',
    },
    {
      context: { queryType: 'anime.movie', isAnime: true },
      expr: `queryType=='anime.movie' ? quality(streams, "BluRay REMUX") : []`,
      label: 'anime.movie guard under anime.movie query',
    },
    {
      context: { queryType: 'anime.series', isAnime: true },
      expr: `queryType=='anime.series' ? quality(streams, "BluRay REMUX") : []`,
      label: 'anime.series guard under anime.series query',
    },
  ];

  console.log('\n== guard regression check ==');
  for (const { context, expr, label } of checks) {
    const selector = new StreamSelector(context);
    const selected = await selector.select([fixture], expr);
    const ok = label.startsWith('plain') ? selected.length === 0 : selected.length > 0;
    if (!ok) bad += 1;
    console.log(
      `  ${ok ? 'PASS' : 'FAIL'}  ${label}: selected=${selected.length}`
    );
  }
  return bad;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
const targets = process.argv.slice(2);
const animeProfiles = targets.length
  ? targets
  : readdirSync(PROFILES_DIR)
      .filter((f) => f.endsWith('.expressions.json'))
      .filter((f) => f.startsWith('anime-'))
      .map((f) => join(PROFILES_DIR, f));

/** The queryTypes a profile is served under. Anime profiles get the
 * anime-scoped types; everything else gets plain movie/series. */
function intendedQueryTypes(profilePath) {
  const base = profilePath.split('/').pop() ?? profilePath;
  return base.startsWith('anime-')
    ? ['anime.movie', 'anime.series']
    : ['movie', 'series'];
}

let allOk = true;
for (const p of animeProfiles) {
  const res = await evaluateProfile(p, intendedQueryTypes(p));
  const nonZeroQts = Object.entries(res.scoreByQt).filter(
    ([, s]) => s > 0
  );
  const totalScore = Object.values(res.scoreByQt).reduce((a, b) => a + b, 0);
  const matchedTotal = Object.values(res.matchedCountByQt).reduce(
    (a, b) => a + b,
    0
  );
  const ok = res.failures === 0 && totalScore > 0 && nonZeroQts.length > 0;

  console.log(`\n== ${p.split('/').pop()} ==`);
  console.log(`  enabled items      : ${res.enabledItems}`);
  console.log(`  regexes matched    : ${res.regexesMatched.length} (${res.regexesMatched.slice(0, 12).join(', ')}${res.regexesMatched.length > 12 ? ', ...' : ''})`);
  for (const [qt, score] of Object.entries(res.scoreByQt)) {
    console.log(`  queryType='${qt}': score=${score} matchedExprs=${res.matchedCountByQt[qt]}`);
  }
  console.log(`  TOTAL score        : ${totalScore}`);
  if (res.failures > 0) {
    console.log(`  FAILURES           : ${res.failures}`);
    for (const d of res.failureDetails.slice(0, 5)) console.log(`    - ${d}`);
  }
  console.log(`  RESULT             : ${ok ? 'PASS' : 'FAIL'}`);
  allOk = allOk && ok;
}

const guardBad = await checkAnimeGuards();
console.log(`\n${allOk && guardBad === 0 ? 'ALL PROFILES PASS' : 'SOME PROFILES FAILED'}`);
process.exit(allOk && guardBad === 0 ? 0 : 1);